In [1]:
# http://nghiaho.com/?page_id=671
#!/usr/bin/env python3

import numpy as np
from rigid_transform_3D import rigid_transform_3D

# Test with random data

# Random rotation and translation
R = np.random.rand(3,3)
t = np.random.rand(3,1)

# make R a proper rotation matrix, force orthonormal
U, S, Vt = np.linalg.svd(R)
R = U@Vt

# remove reflection
if np.linalg.det(R) < 0:
   Vt[2,:] *= -1
   R = U@Vt

# number of points
n = 8

A = np.random.rand(3, n)
B = R@A + t

# Recover R and t
ret_R, ret_t = rigid_transform_3D(A, B)

# Compare the recovered R and t with the original
B2 = (ret_R@A) + ret_t

# Find the root mean squared error
err = B2 - B
err = err * err
err = np.sum(err)
rmse = np.sqrt(err/n)

print("Points A")
print(A)
print("")

print("Points B")
print(B)
print("")

print("Ground truth rotation")
print(R)

print("Recovered rotation")
print(ret_R)
print("")

print("Ground truth translation")
print(t)

print("Recovered translation")
print(ret_t)
print("")

print("RMSE:", rmse)

if rmse < 1e-5:
    print("Everything looks good!")
else:
    print("Hmm something doesn't look right ...")

Points A
[[0.04320975 0.56466334 0.79635297 0.78847533 0.416445   0.50378856
  0.31689185 0.32004227]
 [0.64720231 0.63340519 0.74760029 0.55203383 0.99363868 0.29642873
  0.36828196 0.18506536]
 [0.78648107 0.55593163 0.46269161 0.47303243 0.63562449 0.07409308
  0.38388463 0.29794294]]

Points B
[[-0.21786886  0.34440998  0.56802013  0.59401123  0.11184391  0.53341926
   0.23413853  0.30386698]
 [ 0.90154015  0.98435667  1.13376604  0.95511255  1.29080107  0.52893187
   0.62112942  0.43140572]
 [ 0.72149487  0.67415367  0.61856908  0.69487519  0.57369148  0.34813068
   0.54305304  0.53270495]]

Ground truth rotation
[[ 0.9076735  -0.1892698  -0.3745741 ]
 [ 0.30103966  0.91550373  0.26688582]
 [ 0.29241056 -0.35500685  0.8879562 ]]
Recovered rotation
[[ 0.9076735  -0.1892698  -0.3745741 ]
 [ 0.30103966  0.91550373  0.26688582]
 [ 0.29241056 -0.35500685  0.8879562 ]]

Ground truth translation
[[0.16000209]
 [0.08611553]
 [0.2402604 ]]
Recovered translation
[[0.16000209]
 [0.08611553]
